### ISSUE TITLE
Can you give an example of mybatis multi data source support?

### ISSUE THREAD

**Issue by huyaro** [easybest/spring-data-mybatis#151]
Can you give an example of mybatis multi data source support? I saw in the code that AbstractRoutingDataSource has been implemented, but not show how to use it. Thank you very much!

**Comment by easybest** [comment]
#139

**Comment by kopax** [comment]
@althyman I've made a demo repository for multi datasource. See https://github.com/kopax/spring-data-mybatis-test

The most important part is to name your beans and refManager : 

https://github.com/kopax/spring-data-mybatis-test/blob/master/src/main/java/com/domain/api/userManagement/UserManagementDbConfig.java

if you are using `spring-boot-starter-data-mybatis` you must use `@EnableMyBatisRepository`,  you won't be able to specify `transactionManager` ref name without it.

This will also break `beforemappers` if you are using it, because the code responsible for loading them is only available in the starter when you are not using `@EnableMyBatisRepository` but autoconfiguration. 

In that case the solution is to write your own `beforemappers` injection like in the starter. 

This is how my sqlSessionFactory looks like for all my datasources:

```java
    public SqlSessionFactoryBean sqlSessionFactory(String[] beforeMapperLocations) throws Exception {
        final SqlSessionFactoryBean sessionFactory = new SqlSessionFactoryBean();
        sessionFactory.setDataSource(dataSource());

        String[] beforemappers = (String[]) ArrayUtils.addAll(properties.getBeforeMapperLocations(), beforeMapperLocations);
        if (null != beforemappers && beforemappers.length > 0) {
            Set<Resource> set = new HashSet<>();
            for (String s : beforemappers) {
                Resource[] resources = ResourcePatternUtils.getResourcePatternResolver(this.resourceLoader).getResources(s);
                if (null != resources && resources.length > 0) {
                    set.addAll(Arrays.asList(resources));
                }
            }
            if (!set.isEmpty()) {
                sessionFactory.setMapperLocations(set.toArray(new Resource[set.size()]));
            }
        }

        String handlers = "ir.boot.autoconfigure.data.mybatis.handlers";
        if (null != properties.getHandlerPackages() && properties.getHandlerPackages().length > 0) {
            for (String s : properties.getHandlerPackages()) {
                if (StringUtils.isEmpty(s)) {
                    continue;
                }
                handlers += "," + s;
            }

        }

        sessionFactory.setTypeHandlersPackage(handlers);

        org.apache.ibatis.session.Configuration configuration = sessionFactory.getObject().getConfiguration();
        configuration.setMapUnderscoreToCamelCase(true);
        if (null != properties.getDefaultScriptingLanguage()) {
            configuration.setDefaultScriptingLanguage(properties.getDefaultScriptingLanguage());
        }
        return sessionFactory;
    }
```

**Comment by huyaro** [comment]
thank you very much!!  @kopax @hatunet

**Comment by kopax** [comment]
You're welcome, feel free to close the issue if you believe this answer your question.

**Comment by easybest** [comment]
Thank you for your patience. @kopax

**Comment by kopax** [comment]
@hatunet not sure if this is ironic. As I told you last year, I am now in the period where I am actively working on that framework. Would be great if you could have a look back at #152. 
With regards,
