### ISSUE TITLE
support for id auto generation using snowflake

### ISSUE THREAD

**Issue by yezhoujie** [easybest/spring-data-mybatis#181]
support for id auto-generation using snowflake

**Comment by easybest** [comment]
add @Snowflake annotation.

**Comment by easybest** [comment]
see https://github.com/hatunet/spring-data-mybatis/blob/0bebe40ba74d807f621dc7b46380c2abc4b154df/spring-data-mybatis/src/test/java/org/springframework/data/mybatis/domain/sample/Role.java#L20

and 3 preperties support if you use spring-data-mybatis-boot-starter:
```
spring.data.mybatis.repositories.snowflake.enabled
spring.data.mybatis.repositories.snowflake.datacenterId
spring.data.mybatis.repositories.snowflake.workerId

```

otherwise, you can create Snowflake bean by yourself. (please use org.springframework.data.mybatis.id.Snowflake)
