### ISSUE TITLE
support  @CreatedBy and @LastModifiedBy to audit entity automatically

### ISSUE THREAD

**Issue by easybest** [easybest/spring-data-mybatis#55]

**Comment by kopax** [comment]
Could you please share some example of configuration (schema and entity) ?

I have tested it with : 

```java
@CreatedBy
@Column(name = "MANAGER_CREATION_ID")
@JdbcType(BIGINT)
private Long managerCreationId;
```

and 

```sql
"CREATION_DATETIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
"MANAGER_CREATION_ID" BIGINT DEFAULT NULL,
"MODIFICATION_DATETIME" TIMESTAMP DEFAULT NULL,
"MANAGER_MODIFICATION_ID" BIGINT DEFAULT NULL,
```

Calling `repository.save(entity)` left theses column to null

**Comment by easybest** [comment]
@kopax

you should implement interface : AuditorAware<T>

and register it as a spring bean.

a simple's one like this : 

```java
@Bean
    public AuditorAware<Long> auditorAware() {
        return new AuditorAware<Long>() {
            @Override
            public Long getCurrentAuditor() {
                return 1001L; // here should change to your logic , from my experience it need combine with some security framework
            }
        };
    }
```

**Comment by kopax** [comment]
Yeap, I am currently working on it

I found this : http://docs.spring.io/spring-data/data-jpa/docs/1.7.0.DATAJPA-580-SNAPSHOT/reference/html/auditing.html and https://github.com/hatunet/spring-data-mybatis/blob/ab6e3da7cfd83566d2f2a4818ba5012830a303b3/src/test/java/org/springframework/data/mybatis/config/sample/TestConfig.java#L68

Leading me to 

```java

	@Bean
	public AuditorAware<Long> auditorAware() {
		return new AuditorAware<Long>() {
			@Override
			public Long getCurrentAuditor() {
				Authentication authentication = SecurityContextHolder.getContext().getAuthentication();

				if (authentication == null || !authentication.isAuthenticated()) {
					return null;
				}

				UserDetails userDetails = (UserDetails) authentication.getPrincipal();
				return 1L;
			}
		};
	}
```

No matter what I try in this function, the cast fail pretending to be a String instead of my user object.
I am using basic spring security with a UserDetailsService.
